name: vortexdb
description: Object database

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  binary_data:
    path: ../BinaryData
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0 
  test: ^1.6.0
